---
- name: Create a new EC2 instance
  hosts: localhost
  gather_facts: no
  vars:
    ANSIBLE_COLLECTIONS_PATHS:
      - /home/ansawx/.ansible/collections
      - /home/ansawx/.local/lib/python3.9/site-packages/ansible_collections
  collections:
    - amazon.aws

  tasks:
    - name: Create a new EC2 instance
      amazon.aws.ec2_instance:
        region: "{{ ec2_region }}"
        instance_type: "{{ ec2_instance_type }}"
        image_id: "{{ ec2_image_id }}"
        key_name: "{{ ec2_key_name }}"
        security_group: "{{ ec2_security_group }}"
        count: 1
        wait: yes
        tags:
          Name: "{{ ec2_instance_name }}"
      register: ec2_instance
      ignore_errors: yes
      connection: local

    - name: Print the instance public IP
      debug:
        msg: "Public IP: {{ ec2_instance.instance.public_ip }}"
      when: ec2_instance is defined and ec2_instance.instance.public_ip is defined
