---
- name: Create a new EC2 instance
  hosts: localhost
  gather_facts: no
  collections:
    - amazon.aws
  tasks:
    - name: Create a new EC2 instance
      ec2_instance:
        region: "{{ ec2_region }}"
        instance_type: "{{ ec2_instance_type }}"
        image_id: "{{ ec2_image_id }}"
        key_name: "{{ ec2_key_name }}"
        security_group: "{{ ec2_security_group }}"
        wait: yes
        tags:
          Name: "{{ ec2_instance_name }}"
      register: ec2_instance_info

    - set_fact:
        id: "{{ ec2_instance_info }}"

    - name: Wait for the instance to be running
      ec2_instance_info:
        filters:
          "tag:Name": "{{ ec2_instance_name }}"
        register: ec2_instance_info_detail
        until: ec2_instance_info_detail.instances[0].state.name == 'running'
        retries: 30
        delay: 10

      
    - name: Print the instance public IP
      debug:
        msg: "Public IP: {{ ec2_instance.instance.public_ip }}"
      when: ec2_instance is defined and ec2_instance.instance.public_ip is defined
