---
- name: Create a new EC2 instance
  hosts: localhost
  gather_facts: no
  collections:
    - amazon.aws
  tasks:
    - name: Create a new EC2 instance
      ec2_instance:
        region: "{{ ec2_region }}"
        instance_type: "{{ ec2_instance_type }}"
        image_id: "{{ ec2_image_id }}"
        key_name: "{{ ec2_key_name }}"
        security_group: "{{ ec2_security_group }}"
        wait: yes
        tags:
          Name: "{{ ec2_instance_name }}"
      loop:
        - 0
      register: ec2_instance
      ignore_errors: yes
      connection: local
      vars:
        ansible_python_interpreter: /usr/bin/python3

    - name: Print the instance public IP
      debug:
        msg: "Public IP: {{ ec2_instance.instance.public_ip }}"
      when: ec2_instance is defined and ec2_instance.instance.public_ip is defined
