---
- name: Gather EC2 instance details
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Get all EC2 instance information
      ec2_instance_info:
        region: "{{ region_name }}"
      register: my_instance_list


    - name: Debug ec2_instances variable
      debug:
        var: my_instance_list
        
    - name: Display instance details in tabular format
      debug:
        msg: "{{ my_instance_list.instance_id }} | {{ my_instance_list.tags.Name | default('N/A') }} | {{ my_instance_list.instance_type }} | {{ my_instance_list.state.name }} | {{ my_instance_list.private_ip_address }} | {{ my_instance_list.public_ip_address }} | {{ my_instance_list.security_groups[0].group_name }} | {{ region_name }}"
      loop: "{{ my_instance_list.instances }}"
