---
- name: Gather EC2 instance details
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Get all EC2 instance information
      ec2_instance_info:
        region: "{{ region_name }}"
      register: my_instance_list


    - name: Debug ec2_instances variable
      debug:
        var: my_instance_list
        
    - name: Display instance details in tabular format
      debug:
        msg: |
          {% set instances = my_instance_list.instances %}
          {% if instances %}
          Instance ID      | Instance Name        | Instance Type | State    | Security Groups    | Region
          ----------------|----------------------|---------------|----------|--------------------|-------
          {% for instance in instances %}
          {{ instance.id }} | {{ instance.tags.Name | default('N/A') }} | {{ instance.instance_type }} | {{ instance.state.name }} | {{ instance.security_groups | map(attribute='group_name') | join(', ') }} | {{ instance.region }}
          {% endfor %}
          {% else %}
          No instances found.
          {% endif %}
